import enum

PROTOCOL_VERSION = 49


class SocketEvents:
    class Incoming(enum.IntEnum):
        PING_DATA = 1
        ROOM_CREATE = 2
        ROOM_JOIN = 3
        PLAYER_JOIN = 4
        PLAYER_LEFT = 5
        HOST_LEFT = 6
        PLAYER_MOVE = 7
        READY_CHANGE = 8
        READY_RESET = 9
        PLAYER_MUTE = 10
        PLAYER_UNMUTE = 11
        PLAYER_NAME_CHANGE = 12
        GAME_END = 13
        # Packet 14
        GAME_START = 15
        STATUS = 16
        # Packet 17
        PLAYER_TEAM_CHANGE = 18
        TEAM_LOCK = 19
        MESSAGE = 20
        INFORM_IN_LOBBY = 21
        TIME_SYNC = 23
        KICK = 24
        MAP_REORDER = 25
        MODE_CHANGE = 26
        ROUNDS_CHANGE = 27
        MAP_DELETE = 28
        MAP_CHANGE = 29
        TYPING = 30
        ADMIN_INPUTS = 31
        AFK_WARN = 32
        MAP_SUGGEST_HOST = 33
        MAP_SUGGEST_CLIENT = 34
        CHANGE_MODE = 35
        SET_BALANCE = 36
        # Packet 37
        DEBUG_WINNER = 38
        TEAMS_TOGGLE = 39
        REPLAY_RECORD = 40
        HOST_CHANGE = 41
        FRIEND_REQUEST = 42
        COUNTDOWN = 43
        COUNTDOWN_ABORT = 44
        LEVEL_UP = 45
        XP_GAIN = 46
        LOCAL_REVERT = 47
        INFORM_IN_GAME = 48
        ROOM_ID_OBTAIN = 49
        MAP_VOTE = 50
        MORE_QUICK_MAPS = 51
        PLAYER_TABBED = 52
        DESYNC_REQ = 53
        DESYNC_RES = 54
        CURATE_RESULT = 57
        ROOM_NAME_CHANGE = 58
        ROOM_PASS_CHANGE = 59
        SERVER_MESSAGE = 60

    class Outgoing(enum.IntEnum):
        PING_DATA = 1
        TEST_PING = 2
        GET_DEBUG = 3
        MOVE = 4
        GAME_START = 5
        SET_OWN_TEAM = 6
        SET_TEAM_LOCK = 7
        MUTE = 8
        BAN = 9
        SEND_MESSAGE = 10
        INFORM_IN_LOBBY = 11
        CREATE_ROOM = 12
        JOIN_ROOM = 13
        RETURN_TO_LOBBY = 14
        SET_READY = 16
        RESET_READY = 17
        TIME_SYNC = 18
        MAP_REORDER = 19
        SET_MODE = 20
        SET_ROUNDS = 21
        MAP_DELETE = 22
        MAP_ADD = 23
        TYPING = 24
        ADMIN_INPUTS = 25
        SET_OTHER_TEAM = 26
        MAP_SUGGEST = 27
        CHANGE_MODE = 28
        SET_BALANCE = 29
        VERSION_CHECK = 30
        DEBUG_WINNER = 31
        SET_TEAM_STATE = 32
        RECORD_REPLAY = 33
        GIVE_HOST = 34
        FRIEND_REQUEST = 35
        COUNTDOWN = 36
        ABORT_COUNTDOWN = 37
        XP_GAIN = 38
        MAP_VOTE = 39
        INFORM_IN_GAME = 40
        PRE_VOTE = 41
        MORE_QUICK_MAPS = 42
        UPDATE_RC = 43  # Update quick play map
        SET_TABBED = 44
        DESYNC_TEST = 45
        DESYNC_RES = 46
        ROUND_COMPLETE = 47  # Idk whats round but its not just round in game
        END_ROOM = 50
        CURATE = 51
        CHANGE_ROOM_NAME = 52
        CHANGE_ROOM_PASS = 53
